// flow-typed signature: b4cee1c29051f4792fab86e118efc644
// flow-typed version: <<STUB>>/react-bootstrap_v0.30.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-bootstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-bootstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-bootstrap/react-bootstrap' {
  declare module.exports: any;
}

declare module 'react-bootstrap/react-bootstrap.min' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Accordion' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Alert' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Badge' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Breadcrumb' {
  declare module.exports: any;
}

declare module 'react-bootstrap/BreadcrumbItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Button' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ButtonGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ButtonToolbar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Carousel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/CarouselCaption' {
  declare module.exports: any;
}

declare module 'react-bootstrap/CarouselItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Checkbox' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Clearfix' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Col' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Collapse' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ControlLabel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Dropdown' {
  declare module.exports: any;
}

declare module 'react-bootstrap/DropdownButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/DropdownMenu' {
  declare module.exports: any;
}

declare module 'react-bootstrap/DropdownToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Fade' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Form' {
  declare module.exports: any;
}

declare module 'react-bootstrap/FormControl' {
  declare module.exports: any;
}

declare module 'react-bootstrap/FormControlFeedback' {
  declare module.exports: any;
}

declare module 'react-bootstrap/FormControlStatic' {
  declare module.exports: any;
}

declare module 'react-bootstrap/FormGroup' {
  declare module.exports: any;
}


declare module 'react-bootstrap/Glyphicon' {
  declare class Glyphicon extends React$Component {
    props: {
      glyph: string
    };
  }
  declare module.exports: Class<Glyphicon>;
}


declare module 'react-bootstrap/Grid' {
  declare module.exports: any;
}

declare module 'react-bootstrap/HelpBlock' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Image' {
  declare module.exports: any;
}

declare module 'react-bootstrap/InputGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/InputGroupAddon' {
  declare module.exports: any;
}

declare module 'react-bootstrap/InputGroupButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Jumbotron' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Label' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ListGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ListGroupItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Media' {
  declare module.exports: any;
}

declare module 'react-bootstrap/MediaBody' {
  declare module.exports: any;
}

declare module 'react-bootstrap/MediaHeading' {
  declare module.exports: any;
}

declare module 'react-bootstrap/MediaLeft' {
  declare module.exports: any;
}

declare module 'react-bootstrap/MediaList' {
  declare module.exports: any;
}

declare module 'react-bootstrap/MediaListItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/MediaRight' {
  declare module.exports: any;
}

declare module 'react-bootstrap/MenuItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Modal' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ModalBody' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ModalDialog' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ModalFooter' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ModalHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ModalTitle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Nav' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Navbar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/NavbarBrand' {
  declare module.exports: any;
}

declare module 'react-bootstrap/NavbarCollapse' {
  declare module.exports: any;
}

declare module 'react-bootstrap/NavbarHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/NavbarToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/NavDropdown' {
  declare module.exports: any;
}

declare module 'react-bootstrap/NavItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Overlay' {
  declare module.exports: any;
}

declare module 'react-bootstrap/OverlayTrigger' {
  declare module.exports: any;
}

declare module 'react-bootstrap/PageHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/PageItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Pager' {
  declare module.exports: any;
}

declare module 'react-bootstrap/PagerItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Pagination' {
  declare module.exports: any;
}

declare module 'react-bootstrap/PaginationButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Panel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/PanelGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Popover' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Radio' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ResponsiveEmbed' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Row' {
  declare module.exports: any;
}

declare module 'react-bootstrap/SafeAnchor' {
  declare module.exports: any;
}

declare module 'react-bootstrap/SplitButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/SplitToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Tab' {
  declare module.exports: any;
}

declare module 'react-bootstrap/TabContainer' {
  declare module.exports: any;
}

declare module 'react-bootstrap/TabContent' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Table' {
  declare module.exports: any;
}

declare module 'react-bootstrap/TabPane' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Tabs' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Thumbnail' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Tooltip' {
  declare module.exports: any;
}

declare module 'react-bootstrap/bootstrapUtils' {
  declare module.exports: any;
}

declare module 'react-bootstrap/capitalize' {
  declare module.exports: any;
}

declare module 'react-bootstrap/createChainedFunction' {
  declare module.exports: any;
}

declare module 'react-bootstrap/deprecationWarning' {
  declare module.exports: any;
}

declare module 'react-bootstrap/PropTypes' {
  declare module.exports: any;
}

declare module 'react-bootstrap/splitComponentProps' {
  declare module.exports: any;
}

declare module 'react-bootstrap/StyleConfig' {
  declare module.exports: any;
}

declare module 'react-bootstrap/TransitionEvents' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ValidComponentChildren' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Well' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Accordion' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Alert' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Badge' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Breadcrumb' {
  declare module.exports: any;
}

declare module 'react-bootstrap/BreadcrumbItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Button' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ButtonGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ButtonToolbar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Carousel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/CarouselCaption' {
  declare module.exports: any;
}

declare module 'react-bootstrap/CarouselItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Checkbox' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Clearfix' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Col' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Collapse' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ControlLabel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Dropdown' {
  declare module.exports: any;
}

declare module 'react-bootstrap/DropdownButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/DropdownMenu' {
  declare module.exports: any;
}

declare module 'react-bootstrap/DropdownToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Fade' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Form' {
  declare module.exports: any;
}

declare module 'react-bootstrap/FormControl' {
  declare module.exports: any;
}

declare module 'react-bootstrap/FormControlFeedback' {
  declare module.exports: any;
}

declare module 'react-bootstrap/FormControlStatic' {
  declare module.exports: any;
}

declare module 'react-bootstrap/FormGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Glyphicon' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Grid' {
  declare module.exports: any;
}

declare module 'react-bootstrap/HelpBlock' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Image' {
  declare module.exports: any;
}

declare module 'react-bootstrap/InputGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/InputGroupAddon' {
  declare module.exports: any;
}

declare module 'react-bootstrap/InputGroupButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Jumbotron' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Label' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ListGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ListGroupItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Media' {
  declare module.exports: any;
}

declare module 'react-bootstrap/MediaBody' {
  declare module.exports: any;
}

declare module 'react-bootstrap/MediaHeading' {
  declare module.exports: any;
}

declare module 'react-bootstrap/MediaLeft' {
  declare module.exports: any;
}

declare module 'react-bootstrap/MediaList' {
  declare module.exports: any;
}

declare module 'react-bootstrap/MediaListItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/MediaRight' {
  declare module.exports: any;
}

declare module 'react-bootstrap/MenuItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Modal' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ModalBody' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ModalDialog' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ModalFooter' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ModalHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ModalTitle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Nav' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Navbar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/NavbarBrand' {
  declare module.exports: any;
}

declare module 'react-bootstrap/NavbarCollapse' {
  declare module.exports: any;
}

declare module 'react-bootstrap/NavbarHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/NavbarToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/NavDropdown' {
  declare module.exports: any;
}

declare module 'react-bootstrap/NavItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Overlay' {
  declare module.exports: any;
}

declare module 'react-bootstrap/OverlayTrigger' {
  declare module.exports: any;
}

declare module 'react-bootstrap/PageHeader' {
  declare module.exports: any;
}

declare module 'react-bootstrap/PageItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Pager' {
  declare module.exports: any;
}

declare module 'react-bootstrap/PagerItem' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Pagination' {
  declare module.exports: any;
}

declare module 'react-bootstrap/PaginationButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Panel' {
  declare module.exports: any;
}

declare module 'react-bootstrap/PanelGroup' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Popover' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Radio' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ResponsiveEmbed' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Row' {
  declare module.exports: any;
}

declare module 'react-bootstrap/SafeAnchor' {
  declare module.exports: any;
}

declare module 'react-bootstrap/SplitButton' {
  declare module.exports: any;
}

declare module 'react-bootstrap/SplitToggle' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Tab' {
  declare module.exports: any;
}

declare module 'react-bootstrap/TabContainer' {
  declare module.exports: any;
}

declare module 'react-bootstrap/TabContent' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Table' {
  declare module.exports: any;
}

declare module 'react-bootstrap/TabPane' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Tabs' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Thumbnail' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Tooltip' {
  declare module.exports: any;
}

declare module 'react-bootstrap/bootstrapUtils' {
  declare module.exports: any;
}

declare module 'react-bootstrap/capitalize' {
  declare module.exports: any;
}

declare module 'react-bootstrap/createChainedFunction' {
  declare module.exports: any;
}

declare module 'react-bootstrap/deprecationWarning' {
  declare module.exports: any;
}

declare module 'react-bootstrap/PropTypes' {
  declare module.exports: any;
}

declare module 'react-bootstrap/splitComponentProps' {
  declare module.exports: any;
}

declare module 'react-bootstrap/StyleConfig' {
  declare module.exports: any;
}

declare module 'react-bootstrap/TransitionEvents' {
  declare module.exports: any;
}

declare module 'react-bootstrap/ValidComponentChildren' {
  declare module.exports: any;
}

declare module 'react-bootstrap/Well' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-bootstrap/react-bootstrap.js' {
  declare module.exports: $Exports<'react-bootstrap/react-bootstrap'>;
}
declare module 'react-bootstrap/react-bootstrap.min.js' {
  declare module.exports: $Exports<'react-bootstrap/react-bootstrap.min'>;
}
declare module 'react-bootstrap/Accordion.js' {
  declare module.exports: $Exports<'react-bootstrap/Accordion'>;
}
declare module 'react-bootstrap/Alert.js' {
  declare module.exports: $Exports<'react-bootstrap/Alert'>;
}
declare module 'react-bootstrap/Badge.js' {
  declare module.exports: $Exports<'react-bootstrap/Badge'>;
}
declare module 'react-bootstrap/Breadcrumb.js' {
  declare module.exports: $Exports<'react-bootstrap/Breadcrumb'>;
}
declare module 'react-bootstrap/BreadcrumbItem.js' {
  declare module.exports: $Exports<'react-bootstrap/BreadcrumbItem'>;
}
declare module 'react-bootstrap/Button.js' {
  declare module.exports: $Exports<'react-bootstrap/Button'>;
}
declare module 'react-bootstrap/ButtonGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/ButtonGroup'>;
}
declare module 'react-bootstrap/ButtonToolbar.js' {
  declare module.exports: $Exports<'react-bootstrap/ButtonToolbar'>;
}
declare module 'react-bootstrap/Carousel.js' {
  declare module.exports: $Exports<'react-bootstrap/Carousel'>;
}
declare module 'react-bootstrap/CarouselCaption.js' {
  declare module.exports: $Exports<'react-bootstrap/CarouselCaption'>;
}
declare module 'react-bootstrap/CarouselItem.js' {
  declare module.exports: $Exports<'react-bootstrap/CarouselItem'>;
}
declare module 'react-bootstrap/Checkbox.js' {
  declare module.exports: $Exports<'react-bootstrap/Checkbox'>;
}
declare module 'react-bootstrap/Clearfix.js' {
  declare module.exports: $Exports<'react-bootstrap/Clearfix'>;
}
declare module 'react-bootstrap/Col.js' {
  declare module.exports: $Exports<'react-bootstrap/Col'>;
}
declare module 'react-bootstrap/Collapse.js' {
  declare module.exports: $Exports<'react-bootstrap/Collapse'>;
}
declare module 'react-bootstrap/ControlLabel.js' {
  declare module.exports: $Exports<'react-bootstrap/ControlLabel'>;
}
declare module 'react-bootstrap/Dropdown.js' {
  declare module.exports: $Exports<'react-bootstrap/Dropdown'>;
}
declare module 'react-bootstrap/DropdownButton.js' {
  declare module.exports: $Exports<'react-bootstrap/DropdownButton'>;
}
declare module 'react-bootstrap/DropdownMenu.js' {
  declare module.exports: $Exports<'react-bootstrap/DropdownMenu'>;
}
declare module 'react-bootstrap/DropdownToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/DropdownToggle'>;
}
declare module 'react-bootstrap/Fade.js' {
  declare module.exports: $Exports<'react-bootstrap/Fade'>;
}
declare module 'react-bootstrap/Form.js' {
  declare module.exports: $Exports<'react-bootstrap/Form'>;
}
declare module 'react-bootstrap/FormControl.js' {
  declare module.exports: $Exports<'react-bootstrap/FormControl'>;
}
declare module 'react-bootstrap/FormControlFeedback.js' {
  declare module.exports: $Exports<'react-bootstrap/FormControlFeedback'>;
}
declare module 'react-bootstrap/FormControlStatic.js' {
  declare module.exports: $Exports<'react-bootstrap/FormControlStatic'>;
}
declare module 'react-bootstrap/FormGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/FormGroup'>;
}
declare module 'react-bootstrap/Glyphicon.js' {
  declare module.exports: $Exports<'react-bootstrap/Glyphicon'>;
}
declare module 'react-bootstrap/Grid.js' {
  declare module.exports: $Exports<'react-bootstrap/Grid'>;
}
declare module 'react-bootstrap/HelpBlock.js' {
  declare module.exports: $Exports<'react-bootstrap/HelpBlock'>;
}
declare module 'react-bootstrap/Image.js' {
  declare module.exports: $Exports<'react-bootstrap/Image'>;
}
declare module 'react-bootstrap/index' {
  declare module.exports: $Exports<'react-bootstrap'>;
}
declare module 'react-bootstrap/index.js' {
  declare module.exports: $Exports<'react-bootstrap'>;
}
declare module 'react-bootstrap/InputGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/InputGroup'>;
}
declare module 'react-bootstrap/InputGroupAddon.js' {
  declare module.exports: $Exports<'react-bootstrap/InputGroupAddon'>;
}
declare module 'react-bootstrap/InputGroupButton.js' {
  declare module.exports: $Exports<'react-bootstrap/InputGroupButton'>;
}
declare module 'react-bootstrap/Jumbotron.js' {
  declare module.exports: $Exports<'react-bootstrap/Jumbotron'>;
}
declare module 'react-bootstrap/Label.js' {
  declare module.exports: $Exports<'react-bootstrap/Label'>;
}
declare module 'react-bootstrap/ListGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/ListGroup'>;
}
declare module 'react-bootstrap/ListGroupItem.js' {
  declare module.exports: $Exports<'react-bootstrap/ListGroupItem'>;
}
declare module 'react-bootstrap/Media.js' {
  declare module.exports: $Exports<'react-bootstrap/Media'>;
}
declare module 'react-bootstrap/MediaBody.js' {
  declare module.exports: $Exports<'react-bootstrap/MediaBody'>;
}
declare module 'react-bootstrap/MediaHeading.js' {
  declare module.exports: $Exports<'react-bootstrap/MediaHeading'>;
}
declare module 'react-bootstrap/MediaLeft.js' {
  declare module.exports: $Exports<'react-bootstrap/MediaLeft'>;
}
declare module 'react-bootstrap/MediaList.js' {
  declare module.exports: $Exports<'react-bootstrap/MediaList'>;
}
declare module 'react-bootstrap/MediaListItem.js' {
  declare module.exports: $Exports<'react-bootstrap/MediaListItem'>;
}
declare module 'react-bootstrap/MediaRight.js' {
  declare module.exports: $Exports<'react-bootstrap/MediaRight'>;
}
declare module 'react-bootstrap/MenuItem.js' {
  declare module.exports: $Exports<'react-bootstrap/MenuItem'>;
}
declare module 'react-bootstrap/Modal.js' {
  declare module.exports: $Exports<'react-bootstrap/Modal'>;
}
declare module 'react-bootstrap/ModalBody.js' {
  declare module.exports: $Exports<'react-bootstrap/ModalBody'>;
}
declare module 'react-bootstrap/ModalDialog.js' {
  declare module.exports: $Exports<'react-bootstrap/ModalDialog'>;
}
declare module 'react-bootstrap/ModalFooter.js' {
  declare module.exports: $Exports<'react-bootstrap/ModalFooter'>;
}
declare module 'react-bootstrap/ModalHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/ModalHeader'>;
}
declare module 'react-bootstrap/ModalTitle.js' {
  declare module.exports: $Exports<'react-bootstrap/ModalTitle'>;
}
declare module 'react-bootstrap/Nav.js' {
  declare module.exports: $Exports<'react-bootstrap/Nav'>;
}
declare module 'react-bootstrap/Navbar.js' {
  declare module.exports: $Exports<'react-bootstrap/Navbar'>;
}
declare module 'react-bootstrap/NavbarBrand.js' {
  declare module.exports: $Exports<'react-bootstrap/NavbarBrand'>;
}
declare module 'react-bootstrap/NavbarCollapse.js' {
  declare module.exports: $Exports<'react-bootstrap/NavbarCollapse'>;
}
declare module 'react-bootstrap/NavbarHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/NavbarHeader'>;
}
declare module 'react-bootstrap/NavbarToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/NavbarToggle'>;
}
declare module 'react-bootstrap/NavDropdown.js' {
  declare module.exports: $Exports<'react-bootstrap/NavDropdown'>;
}
declare module 'react-bootstrap/NavItem.js' {
  declare module.exports: $Exports<'react-bootstrap/NavItem'>;
}
declare module 'react-bootstrap/Overlay.js' {
  declare module.exports: $Exports<'react-bootstrap/Overlay'>;
}
declare module 'react-bootstrap/OverlayTrigger.js' {
  declare module.exports: $Exports<'react-bootstrap/OverlayTrigger'>;
}
declare module 'react-bootstrap/PageHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/PageHeader'>;
}
declare module 'react-bootstrap/PageItem.js' {
  declare module.exports: $Exports<'react-bootstrap/PageItem'>;
}
declare module 'react-bootstrap/Pager.js' {
  declare module.exports: $Exports<'react-bootstrap/Pager'>;
}
declare module 'react-bootstrap/PagerItem.js' {
  declare module.exports: $Exports<'react-bootstrap/PagerItem'>;
}
declare module 'react-bootstrap/Pagination.js' {
  declare module.exports: $Exports<'react-bootstrap/Pagination'>;
}
declare module 'react-bootstrap/PaginationButton.js' {
  declare module.exports: $Exports<'react-bootstrap/PaginationButton'>;
}
declare module 'react-bootstrap/Panel.js' {
  declare module.exports: $Exports<'react-bootstrap/Panel'>;
}
declare module 'react-bootstrap/PanelGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/PanelGroup'>;
}
declare module 'react-bootstrap/Popover.js' {
  declare module.exports: $Exports<'react-bootstrap/Popover'>;
}
declare module 'react-bootstrap/ProgressBar.js' {
  declare module.exports: $Exports<'react-bootstrap/ProgressBar'>;
}
declare module 'react-bootstrap/Radio.js' {
  declare module.exports: $Exports<'react-bootstrap/Radio'>;
}
declare module 'react-bootstrap/ResponsiveEmbed.js' {
  declare module.exports: $Exports<'react-bootstrap/ResponsiveEmbed'>;
}
declare module 'react-bootstrap/Row.js' {
  declare module.exports: $Exports<'react-bootstrap/Row'>;
}
declare module 'react-bootstrap/SafeAnchor.js' {
  declare module.exports: $Exports<'react-bootstrap/SafeAnchor'>;
}
declare module 'react-bootstrap/SplitButton.js' {
  declare module.exports: $Exports<'react-bootstrap/SplitButton'>;
}
declare module 'react-bootstrap/SplitToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/SplitToggle'>;
}
declare module 'react-bootstrap/Tab.js' {
  declare module.exports: $Exports<'react-bootstrap/Tab'>;
}
declare module 'react-bootstrap/TabContainer.js' {
  declare module.exports: $Exports<'react-bootstrap/TabContainer'>;
}
declare module 'react-bootstrap/TabContent.js' {
  declare module.exports: $Exports<'react-bootstrap/TabContent'>;
}
declare module 'react-bootstrap/Table.js' {
  declare module.exports: $Exports<'react-bootstrap/Table'>;
}
declare module 'react-bootstrap/TabPane.js' {
  declare module.exports: $Exports<'react-bootstrap/TabPane'>;
}
declare module 'react-bootstrap/Tabs.js' {
  declare module.exports: $Exports<'react-bootstrap/Tabs'>;
}
declare module 'react-bootstrap/Thumbnail.js' {
  declare module.exports: $Exports<'react-bootstrap/Thumbnail'>;
}
declare module 'react-bootstrap/Tooltip.js' {
  declare module.exports: $Exports<'react-bootstrap/Tooltip'>;
}
declare module 'react-bootstrap/bootstrapUtils.js' {
  declare module.exports: $Exports<'react-bootstrap/bootstrapUtils'>;
}
declare module 'react-bootstrap/capitalize.js' {
  declare module.exports: $Exports<'react-bootstrap/capitalize'>;
}
declare module 'react-bootstrap/createChainedFunction.js' {
  declare module.exports: $Exports<'react-bootstrap/createChainedFunction'>;
}
declare module 'react-bootstrap/deprecationWarning.js' {
  declare module.exports: $Exports<'react-bootstrap/deprecationWarning'>;
}
declare module 'react-bootstrap/index' {
  declare module.exports: $Exports<'react-bootstrap'>;
}
declare module 'react-bootstrap/index.js' {
  declare module.exports: $Exports<'react-bootstrap'>;
}
declare module 'react-bootstrap/PropTypes.js' {
  declare module.exports: $Exports<'react-bootstrap/PropTypes'>;
}
declare module 'react-bootstrap/splitComponentProps.js' {
  declare module.exports: $Exports<'react-bootstrap/splitComponentProps'>;
}
declare module 'react-bootstrap/StyleConfig.js' {
  declare module.exports: $Exports<'react-bootstrap/StyleConfig'>;
}
declare module 'react-bootstrap/TransitionEvents.js' {
  declare module.exports: $Exports<'react-bootstrap/TransitionEvents'>;
}
declare module 'react-bootstrap/ValidComponentChildren.js' {
  declare module.exports: $Exports<'react-bootstrap/ValidComponentChildren'>;
}
declare module 'react-bootstrap/Well.js' {
  declare module.exports: $Exports<'react-bootstrap/Well'>;
}
declare module 'react-bootstrap/Accordion.js' {
  declare module.exports: $Exports<'react-bootstrap/Accordion'>;
}
declare module 'react-bootstrap/Alert.js' {
  declare module.exports: $Exports<'react-bootstrap/Alert'>;
}
declare module 'react-bootstrap/Badge.js' {
  declare module.exports: $Exports<'react-bootstrap/Badge'>;
}
declare module 'react-bootstrap/Breadcrumb.js' {
  declare module.exports: $Exports<'react-bootstrap/Breadcrumb'>;
}
declare module 'react-bootstrap/BreadcrumbItem.js' {
  declare module.exports: $Exports<'react-bootstrap/BreadcrumbItem'>;
}
declare module 'react-bootstrap/Button.js' {
  declare module.exports: $Exports<'react-bootstrap/Button'>;
}
declare module 'react-bootstrap/ButtonGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/ButtonGroup'>;
}
declare module 'react-bootstrap/ButtonToolbar.js' {
  declare module.exports: $Exports<'react-bootstrap/ButtonToolbar'>;
}
declare module 'react-bootstrap/Carousel.js' {
  declare module.exports: $Exports<'react-bootstrap/Carousel'>;
}
declare module 'react-bootstrap/CarouselCaption.js' {
  declare module.exports: $Exports<'react-bootstrap/CarouselCaption'>;
}
declare module 'react-bootstrap/CarouselItem.js' {
  declare module.exports: $Exports<'react-bootstrap/CarouselItem'>;
}
declare module 'react-bootstrap/Checkbox.js' {
  declare module.exports: $Exports<'react-bootstrap/Checkbox'>;
}
declare module 'react-bootstrap/Clearfix.js' {
  declare module.exports: $Exports<'react-bootstrap/Clearfix'>;
}
declare module 'react-bootstrap/Col.js' {
  declare module.exports: $Exports<'react-bootstrap/Col'>;
}
declare module 'react-bootstrap/Collapse.js' {
  declare module.exports: $Exports<'react-bootstrap/Collapse'>;
}
declare module 'react-bootstrap/ControlLabel.js' {
  declare module.exports: $Exports<'react-bootstrap/ControlLabel'>;
}
declare module 'react-bootstrap/Dropdown.js' {
  declare module.exports: $Exports<'react-bootstrap/Dropdown'>;
}
declare module 'react-bootstrap/DropdownButton.js' {
  declare module.exports: $Exports<'react-bootstrap/DropdownButton'>;
}
declare module 'react-bootstrap/DropdownMenu.js' {
  declare module.exports: $Exports<'react-bootstrap/DropdownMenu'>;
}
declare module 'react-bootstrap/DropdownToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/DropdownToggle'>;
}
declare module 'react-bootstrap/Fade.js' {
  declare module.exports: $Exports<'react-bootstrap/Fade'>;
}
declare module 'react-bootstrap/Form.js' {
  declare module.exports: $Exports<'react-bootstrap/Form'>;
}
declare module 'react-bootstrap/FormControl.js' {
  declare module.exports: $Exports<'react-bootstrap/FormControl'>;
}
declare module 'react-bootstrap/FormControlFeedback.js' {
  declare module.exports: $Exports<'react-bootstrap/FormControlFeedback'>;
}
declare module 'react-bootstrap/FormControlStatic.js' {
  declare module.exports: $Exports<'react-bootstrap/FormControlStatic'>;
}
declare module 'react-bootstrap/FormGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/FormGroup'>;
}
declare module 'react-bootstrap/Glyphicon.js' {
  declare module.exports: $Exports<'react-bootstrap/Glyphicon'>;
}
declare module 'react-bootstrap/Grid.js' {
  declare module.exports: $Exports<'react-bootstrap/Grid'>;
}
declare module 'react-bootstrap/HelpBlock.js' {
  declare module.exports: $Exports<'react-bootstrap/HelpBlock'>;
}
declare module 'react-bootstrap/Image.js' {
  declare module.exports: $Exports<'react-bootstrap/Image'>;
}
declare module 'react-bootstrap/index' {
  declare module.exports: $Exports<'react-bootstrap'>;
}
declare module 'react-bootstrap/index.js' {
  declare module.exports: $Exports<'react-bootstrap'>;
}
declare module 'react-bootstrap/InputGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/InputGroup'>;
}
declare module 'react-bootstrap/InputGroupAddon.js' {
  declare module.exports: $Exports<'react-bootstrap/InputGroupAddon'>;
}
declare module 'react-bootstrap/InputGroupButton.js' {
  declare module.exports: $Exports<'react-bootstrap/InputGroupButton'>;
}
declare module 'react-bootstrap/Jumbotron.js' {
  declare module.exports: $Exports<'react-bootstrap/Jumbotron'>;
}
declare module 'react-bootstrap/Label.js' {
  declare module.exports: $Exports<'react-bootstrap/Label'>;
}
declare module 'react-bootstrap/ListGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/ListGroup'>;
}
declare module 'react-bootstrap/ListGroupItem.js' {
  declare module.exports: $Exports<'react-bootstrap/ListGroupItem'>;
}
declare module 'react-bootstrap/Media.js' {
  declare module.exports: $Exports<'react-bootstrap/Media'>;
}
declare module 'react-bootstrap/MediaBody.js' {
  declare module.exports: $Exports<'react-bootstrap/MediaBody'>;
}
declare module 'react-bootstrap/MediaHeading.js' {
  declare module.exports: $Exports<'react-bootstrap/MediaHeading'>;
}
declare module 'react-bootstrap/MediaLeft.js' {
  declare module.exports: $Exports<'react-bootstrap/MediaLeft'>;
}
declare module 'react-bootstrap/MediaList.js' {
  declare module.exports: $Exports<'react-bootstrap/MediaList'>;
}
declare module 'react-bootstrap/MediaListItem.js' {
  declare module.exports: $Exports<'react-bootstrap/MediaListItem'>;
}
declare module 'react-bootstrap/MediaRight.js' {
  declare module.exports: $Exports<'react-bootstrap/MediaRight'>;
}
declare module 'react-bootstrap/MenuItem.js' {
  declare module.exports: $Exports<'react-bootstrap/MenuItem'>;
}
declare module 'react-bootstrap/Modal.js' {
  declare module.exports: $Exports<'react-bootstrap/Modal'>;
}
declare module 'react-bootstrap/ModalBody.js' {
  declare module.exports: $Exports<'react-bootstrap/ModalBody'>;
}
declare module 'react-bootstrap/ModalDialog.js' {
  declare module.exports: $Exports<'react-bootstrap/ModalDialog'>;
}
declare module 'react-bootstrap/ModalFooter.js' {
  declare module.exports: $Exports<'react-bootstrap/ModalFooter'>;
}
declare module 'react-bootstrap/ModalHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/ModalHeader'>;
}
declare module 'react-bootstrap/ModalTitle.js' {
  declare module.exports: $Exports<'react-bootstrap/ModalTitle'>;
}
declare module 'react-bootstrap/Nav.js' {
  declare module.exports: $Exports<'react-bootstrap/Nav'>;
}
declare module 'react-bootstrap/Navbar.js' {
  declare module.exports: $Exports<'react-bootstrap/Navbar'>;
}
declare module 'react-bootstrap/NavbarBrand.js' {
  declare module.exports: $Exports<'react-bootstrap/NavbarBrand'>;
}
declare module 'react-bootstrap/NavbarCollapse.js' {
  declare module.exports: $Exports<'react-bootstrap/NavbarCollapse'>;
}
declare module 'react-bootstrap/NavbarHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/NavbarHeader'>;
}
declare module 'react-bootstrap/NavbarToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/NavbarToggle'>;
}
declare module 'react-bootstrap/NavDropdown.js' {
  declare module.exports: $Exports<'react-bootstrap/NavDropdown'>;
}
declare module 'react-bootstrap/NavItem.js' {
  declare module.exports: $Exports<'react-bootstrap/NavItem'>;
}
declare module 'react-bootstrap/Overlay.js' {
  declare module.exports: $Exports<'react-bootstrap/Overlay'>;
}
declare module 'react-bootstrap/OverlayTrigger.js' {
  declare module.exports: $Exports<'react-bootstrap/OverlayTrigger'>;
}
declare module 'react-bootstrap/PageHeader.js' {
  declare module.exports: $Exports<'react-bootstrap/PageHeader'>;
}
declare module 'react-bootstrap/PageItem.js' {
  declare module.exports: $Exports<'react-bootstrap/PageItem'>;
}
declare module 'react-bootstrap/Pager.js' {
  declare module.exports: $Exports<'react-bootstrap/Pager'>;
}
declare module 'react-bootstrap/PagerItem.js' {
  declare module.exports: $Exports<'react-bootstrap/PagerItem'>;
}
declare module 'react-bootstrap/Pagination.js' {
  declare module.exports: $Exports<'react-bootstrap/Pagination'>;
}
declare module 'react-bootstrap/PaginationButton.js' {
  declare module.exports: $Exports<'react-bootstrap/PaginationButton'>;
}
declare module 'react-bootstrap/Panel.js' {
  declare module.exports: $Exports<'react-bootstrap/Panel'>;
}
declare module 'react-bootstrap/PanelGroup.js' {
  declare module.exports: $Exports<'react-bootstrap/PanelGroup'>;
}
declare module 'react-bootstrap/Popover.js' {
  declare module.exports: $Exports<'react-bootstrap/Popover'>;
}
declare module 'react-bootstrap/ProgressBar.js' {
  declare module.exports: $Exports<'react-bootstrap/ProgressBar'>;
}
declare module 'react-bootstrap/Radio.js' {
  declare module.exports: $Exports<'react-bootstrap/Radio'>;
}
declare module 'react-bootstrap/ResponsiveEmbed.js' {
  declare module.exports: $Exports<'react-bootstrap/ResponsiveEmbed'>;
}
declare module 'react-bootstrap/Row.js' {
  declare module.exports: $Exports<'react-bootstrap/Row'>;
}
declare module 'react-bootstrap/SafeAnchor.js' {
  declare module.exports: $Exports<'react-bootstrap/SafeAnchor'>;
}
declare module 'react-bootstrap/SplitButton.js' {
  declare module.exports: $Exports<'react-bootstrap/SplitButton'>;
}
declare module 'react-bootstrap/SplitToggle.js' {
  declare module.exports: $Exports<'react-bootstrap/SplitToggle'>;
}
declare module 'react-bootstrap/Tab.js' {
  declare module.exports: $Exports<'react-bootstrap/Tab'>;
}
declare module 'react-bootstrap/TabContainer.js' {
  declare module.exports: $Exports<'react-bootstrap/TabContainer'>;
}
declare module 'react-bootstrap/TabContent.js' {
  declare module.exports: $Exports<'react-bootstrap/TabContent'>;
}
declare module 'react-bootstrap/Table.js' {
  declare module.exports: $Exports<'react-bootstrap/Table'>;
}
declare module 'react-bootstrap/TabPane.js' {
  declare module.exports: $Exports<'react-bootstrap/TabPane'>;
}
declare module 'react-bootstrap/Tabs.js' {
  declare module.exports: $Exports<'react-bootstrap/Tabs'>;
}
declare module 'react-bootstrap/Thumbnail.js' {
  declare module.exports: $Exports<'react-bootstrap/Thumbnail'>;
}
declare module 'react-bootstrap/Tooltip.js' {
  declare module.exports: $Exports<'react-bootstrap/Tooltip'>;
}
declare module 'react-bootstrap/bootstrapUtils.js' {
  declare module.exports: $Exports<'react-bootstrap/bootstrapUtils'>;
}
declare module 'react-bootstrap/capitalize.js' {
  declare module.exports: $Exports<'react-bootstrap/capitalize'>;
}
declare module 'react-bootstrap/createChainedFunction.js' {
  declare module.exports: $Exports<'react-bootstrap/createChainedFunction'>;
}
declare module 'react-bootstrap/deprecationWarning.js' {
  declare module.exports: $Exports<'react-bootstrap/deprecationWarning'>;
}
declare module 'react-bootstrap/index' {
  declare module.exports: $Exports<'react-bootstrap'>;
}
declare module 'react-bootstrap/index.js' {
  declare module.exports: $Exports<'react-bootstrap'>;
}
declare module 'react-bootstrap/PropTypes.js' {
  declare module.exports: $Exports<'react-bootstrap/PropTypes'>;
}
declare module 'react-bootstrap/splitComponentProps.js' {
  declare module.exports: $Exports<'react-bootstrap/splitComponentProps'>;
}
declare module 'react-bootstrap/StyleConfig.js' {
  declare module.exports: $Exports<'react-bootstrap/StyleConfig'>;
}
declare module 'react-bootstrap/TransitionEvents.js' {
  declare module.exports: $Exports<'react-bootstrap/TransitionEvents'>;
}
declare module 'react-bootstrap/ValidComponentChildren.js' {
  declare module.exports: $Exports<'react-bootstrap/ValidComponentChildren'>;
}
declare module 'react-bootstrap/Well.js' {
  declare module.exports: $Exports<'react-bootstrap/Well'>;
}
